
config = {
    'default_speed': 250,
    'default_station_trade_modifier': 1,
    'default_asteroid_mining_modifier': 300,
    'default_asteroid_mining_radius': 285,
    'progress_required_to_mine': 30,
    'market_fluctuation': 0.01,
    'ore_market_fluctuation': 0.04,
    'ore_value_multiplier': 10,
    'ore_value_random_range': 1,
    'ticks_to_change_economy': 600,
    'server_address': '185.47.65.102',
    'server_port': 8001,
    'ticks_to_update': 10,
    'map_size': 3072,
    'player_start_x': 1536,
    'player_start_y': 1536,
    'asteroid_count': 5,
    'asteroid_replenish_rate': 0.03,
    'max_asteroid_resources': 10,
    'ticks_per_second': 60,
    'station_start_x': 1236,
    'station_start_y': 1536
}

ore_names = [
    "Iron",
    "Copper",
    "Silver",
    "Gold",
    "Platinum",
    "Diamond",
    "Emerald",
    "Ruby",
    "Sapphire",
    "Titanium",
    "Uranium",
    "Plutonium",
    "Tungsten",
    "Tin",
    "Lead",
    "Zinc",
    "Nickel",
    "Cobalt",
    "Chromium",
    "Bismuth",
]
